import MainHeader from "@/components/common/layout/MainHeader";
import NavigationBar from "@/components/common/layout/NavigationBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <>
      <MainHeader />
      {children}
      <NavigationBar />
    </>
  );
};

export default MainLayout;
