import MainHeader from "@/components/main/layout/MainHeader";
import NavigationBar from "@/components/main/layout/NavigationBar";
import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface MainLayoutProps {
  children: Readonly<ReactNode>;
}

const MainLayout = ({ children }: MainLayoutProps) => {
  return (
    <>
      <MainHeader />
      {children}
      <NavigationBar />
    </>
  );
};

export default MainLayout;
