import Header from "@/components/layout/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LogInLayoutProps {
  children: Readonly<React.ReactNode>;
}

const LogInLayout = ({ children }: LogInLayoutProps) => {
  return (
    <>
      <Header />
      {children}
    </>
  );
};

export default LogInLayout;
