import Header from "@/components-temp/layout/Header";
import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LogInLayoutProps {
  children: Readonly<ReactNode>;
}

const LogInLayout = ({ children }: LogInLayoutProps) => {
  return (
    <>
      <Header />
      {children}
    </>
  );
};

export default LogInLayout;
