import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RegisterLatoutProps {
  children: Readonly<ReactNode>;
}

const RegisterLatout = ({ children }: RegisterLatoutProps) => {
  return <>{children}</>;
};

export default RegisterLatout;
