import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RegisterLatoutProps {
  children: Readonly<React.ReactNode>;
}

const RegisterLatout = ({ children }: RegisterLatoutProps) => {
  return <>
    {children}</>;
};

export default RegisterLatout;
