import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthSession from "@/components/providers/SessionProvider";
import Header from "@/components/Home/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="trancy-ko sm:w-[390px] w-full mx-auto">
      <AuthSession>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          {children}
        </body>
      </AuthSession>
    </html>
  );
}
