import type { Metadata } from "next";
import "./globals.css";
import AuthSession from "@/components/providers/SessionProvider";
import Header from "@/components/layout/Header";
import NavigationBar from "@/components/layout/NavigationBar";
import FloatingButton from "@/components/layout/FloatingButton";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`trancy-ko ${pretendard.variable}`}>
      <AuthSession>
        <body className={`antialiased main-contain`}>
          <Header />
          {children}
          <FloatingButton />
          <NavigationBar />
        </body>
      </AuthSession>
    </html>
  );
}
