import Header from "@/components/layout/Header";
import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface MainLayoutProps {
  children: Readonly<ReactNode>;
}

const ResumeLayout = ({ children }: MainLayoutProps) => {
  return (
    <div className="flex h-screen flex-col">
      <Header heading="내 이력" />
      {children}
    </div>
  );
};

export default ResumeLayout;
